name: Build iOS Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: git clone --recursive https://github.com ~/theos

      - name: Setup iOS SDK
        run: |
          git clone https://github.com ~/theos/sdks
          ls -la ~/theos/sdks/

      - name: Compile Tweak
        run: |
          export THEOS=~/theos
          # Принудительно указываем цель под iOS 15.0 и выше
          make package FINALPACKAGE=1 THEOS_DEVICE_ARCHS="arm64" TARGET=iphone:clang:latest:15.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeFire-Menu-Dylib
          path: .theos/obj/debug/*.dylib
